#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

scheduler-docker-local-install() {
  declare desc="install trigger for the scheduler-docker-local plugin"
  local DOKKU_PATH
  DOKKU_PATH=$(which dokku)

  mkdir -p "${DOKKU_LIB_ROOT}/data/scheduler-docker-local"

if [[ $(systemctl 2> /dev/null) =~ -\.mount ]]; then
  cat<<EOF > /etc/systemd/system/dokku-retire.service
[Unit]
Description=Dokku retire service
Requires=docker.service
After=docker.service

[Service]
Type=oneshot
User=$DOKKU_SYSTEM_USER
ExecStart=$DOKKU_PATH ps:restore

[Install]
WantedBy=docker.service
EOF

  cat<<EOF > /etc/systemd/system/dokku-retire.timer
[Unit]
Description=Run dokku-retire.service every 2 minutes

[Timer]
OnCalendar=*:0/2
EOF
  if command -v systemctl &>/dev/null; then
    systemctl reenable dokku-redeploy
  fi
else
  cat<<EOF > /etc/cron.d/dokku-retire
PATH=/usr/local/bin:/usr/bin:/bin
SHELL=/bin/bash

2 * * * * $DOKKU_SYSTEM_USER $DOKKU_PATH ps:retire
EOF
fi
}

scheduler-docker-local-install "$@"
